### ISSUE TITLE
mixed precision training(fp16) support

### ISSUE THREAD

**Issue by ctxqlxs** [sayakpaul/keras-convnext-conversion#3]

**Comment by sayakpaul** [comment]
TensorFlow Hub models don't support training mixed-precision. Cc: @gustheman.


If that is important for your project, you could run the conversion on your end and save the model first. And then you could follow [the official guide](https://www.tensorflow.org/guide/mixed_precision) to proceed further.

**Comment by ctxqlxs** [comment]
I changed some code slightly to adapt to mixed precision training，but it's easy to have OOM problem (the batch_size is same as FP32 training)..

**Comment by sayakpaul** [comment]
That can happen for a lot of reasons. Maybe the variant of the model that you're using is too large to fit on the GPU. 

But the base variant should work okay.

**Comment by ctxqlxs** [comment]
FP32 can train normally, but change to FP16 will OOM(keep anything same as FP32, just add mixed precision training). Is this normal? FP16 should use less memory.

**Comment by sayakpaul** [comment]
Without taking a look at the full code, I can't comment on this. Unfortunately, I don't have the bandwidth to review code now.

**Comment by ctxqlxs** [comment]
I made few changes to the code， just add "tf.cast" to some layer to adapt the mixed precision training.

**Comment by ctxqlxs** [comment]
OK. Thank you anyway!
